/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LightboxPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  minZoom: 0.5,
  maxZoom: 5,
  zoomStep: 0.25
};
var LightboxPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.lightboxEl = null;
    this.currentZoom = 1;
    this.isDragging = false;
    this.startX = 0;
    this.startY = 0;
    this.translateX = 0;
    this.translateY = 0;
    this.contentEl = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerDomEvent(document, "click", (evt) => {
      const target = evt.target;
      if (target.tagName === "IMG" && this.isInReadingView(target)) {
        evt.preventDefault();
        evt.stopPropagation();
        this.openLightbox(target);
        return;
      }
      const mermaidEl = target.closest(".mermaid");
      if (mermaidEl && this.isInReadingView(mermaidEl)) {
        evt.preventDefault();
        evt.stopPropagation();
        this.openMermaidLightbox(mermaidEl);
        return;
      }
    });
    this.registerDomEvent(document, "keydown", (evt) => {
      if (evt.key === "Escape" && this.lightboxEl) {
        this.closeLightbox();
      }
    });
  }
  onunload() {
    this.closeLightbox();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  isInReadingView(el) {
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!markdownView)
      return false;
    const previewEl = markdownView.containerEl.querySelector(".markdown-reading-view");
    if (!previewEl)
      return false;
    return previewEl.contains(el);
  }
  openLightbox(img) {
    this.createLightboxContainer();
    const contentWrapper = this.lightboxEl.querySelector(".lightbox-content-wrapper");
    const imgClone = document.createElement("img");
    imgClone.src = img.src;
    imgClone.alt = img.alt || "";
    imgClone.className = "lightbox-image";
    contentWrapper.appendChild(imgClone);
    this.contentEl = imgClone;
    this.resetZoom();
    this.setupDragHandlers(contentWrapper);
  }
  openMermaidLightbox(mermaidEl) {
    this.createLightboxContainer();
    const contentWrapper = this.lightboxEl.querySelector(".lightbox-content-wrapper");
    const svg = mermaidEl.querySelector("svg");
    if (svg) {
      const svgClone = svg.cloneNode(true);
      svgClone.classList.add("lightbox-mermaid");
      svgClone.classList.add("lightbox-mermaid-content");
      contentWrapper.appendChild(svgClone);
      this.contentEl = svgClone;
    }
    this.resetZoom();
    this.setupDragHandlers(contentWrapper);
  }
  createLightboxContainer() {
    if (this.lightboxEl) {
      this.closeLightbox();
    }
    this.lightboxEl = document.createElement("div");
    this.lightboxEl.className = "lightbox-overlay";
    const contentWrapper = document.createElement("div");
    contentWrapper.className = "lightbox-content-wrapper";
    const controls = document.createElement("div");
    controls.className = "lightbox-controls";
    const zoomOutBtn = document.createElement("button");
    zoomOutBtn.className = "lightbox-btn";
    (0, import_obsidian.setIcon)(zoomOutBtn, "zoom-out");
    zoomOutBtn.title = "Zoom out";
    zoomOutBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.zoomOut();
    });
    const zoomDisplay = document.createElement("span");
    zoomDisplay.className = "lightbox-zoom-display";
    zoomDisplay.textContent = "100%";
    const zoomInBtn = document.createElement("button");
    zoomInBtn.className = "lightbox-btn";
    (0, import_obsidian.setIcon)(zoomInBtn, "zoom-in");
    zoomInBtn.title = "Zoom In";
    zoomInBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.zoomIn();
    });
    const resetBtn = document.createElement("button");
    resetBtn.className = "lightbox-btn";
    (0, import_obsidian.setIcon)(resetBtn, "rotate-ccw");
    resetBtn.title = "Reset";
    resetBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.resetZoom();
    });
    const closeBtn = document.createElement("button");
    closeBtn.className = "lightbox-btn lightbox-close-btn";
    (0, import_obsidian.setIcon)(closeBtn, "x");
    closeBtn.title = "Close";
    closeBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.closeLightbox();
    });
    controls.appendChild(zoomOutBtn);
    controls.appendChild(zoomDisplay);
    controls.appendChild(zoomInBtn);
    controls.appendChild(resetBtn);
    controls.appendChild(closeBtn);
    this.lightboxEl.appendChild(contentWrapper);
    this.lightboxEl.appendChild(controls);
    this.lightboxEl.addEventListener("click", (e) => {
      if (e.target === this.lightboxEl) {
        this.closeLightbox();
      }
    });
    this.lightboxEl.addEventListener("wheel", (e) => {
      e.preventDefault();
      if (e.deltaY < 0) {
        this.zoomIn();
      } else {
        this.zoomOut();
      }
    }, { passive: false });
    document.body.appendChild(this.lightboxEl);
    requestAnimationFrame(() => {
      var _a;
      (_a = this.lightboxEl) == null ? void 0 : _a.classList.add("lightbox-active");
    });
  }
  setupDragHandlers(wrapper) {
    wrapper.addEventListener("mousedown", (e) => {
      if (e.button !== 0)
        return;
      this.isDragging = true;
      this.startX = e.clientX - this.translateX;
      this.startY = e.clientY - this.translateY;
      wrapper.setCssStyles({ cursor: "grabbing" });
    });
    document.addEventListener("mousemove", (e) => {
      if (!this.isDragging)
        return;
      this.translateX = e.clientX - this.startX;
      this.translateY = e.clientY - this.startY;
      this.updateTransform();
    });
    document.addEventListener("mouseup", () => {
      this.isDragging = false;
      if (wrapper) {
        wrapper.setCssStyles({ cursor: "grab" });
      }
    });
  }
  closeLightbox() {
    if (this.lightboxEl) {
      this.lightboxEl.classList.remove("lightbox-active");
      setTimeout(() => {
        var _a;
        (_a = this.lightboxEl) == null ? void 0 : _a.remove();
        this.lightboxEl = null;
        this.contentEl = null;
      }, 200);
    }
    this.resetState();
  }
  resetState() {
    this.currentZoom = 1;
    this.translateX = 0;
    this.translateY = 0;
    this.isDragging = false;
  }
  zoomIn() {
    const newZoom = Math.min(this.currentZoom + this.settings.zoomStep, this.settings.maxZoom);
    this.setZoom(newZoom);
  }
  zoomOut() {
    const newZoom = Math.max(this.currentZoom - this.settings.zoomStep, this.settings.minZoom);
    this.setZoom(newZoom);
  }
  resetZoom() {
    this.currentZoom = 1;
    this.translateX = 0;
    this.translateY = 0;
    this.updateTransform();
    this.updateZoomDisplay();
  }
  setZoom(zoom) {
    this.currentZoom = zoom;
    this.updateTransform();
    this.updateZoomDisplay();
  }
  updateTransform() {
    if (this.contentEl) {
      this.contentEl.setCssStyles({
        transform: `translate(${this.translateX}px, ${this.translateY}px) scale(${this.currentZoom})`
      });
    }
  }
  updateZoomDisplay() {
    if (this.lightboxEl) {
      const display = this.lightboxEl.querySelector(".lightbox-zoom-display");
      if (display) {
        display.textContent = `${Math.round(this.currentZoom * 100)}%`;
      }
    }
  }
};

/* nosourcemap */